# Reference
# exampleSite/config.toml
# exampleSite/full-config.toml
# dev-config.toml
# https://gohugo.io/getting-started/configuration/

buildFuture = true
baseURL = "https://cyrusyip.org/"
title = "Cyrus Yip | 叶寻"
enableRobotsTXT = true
enableEmoji = true
theme = "jane"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]

hasCJKLanguage = true
paginate = 3              # Number of articles displayed on the homepage  # 首页每页显示的文章数
# rssLimit = 20             # Limit Entry Count to Rss file # 限制 Rss 文章输出数量
disqusShortname = "cyrusyip"      # disqus_shortname
googleAnalytics = "UA-193139827-1"      # UA-XXXXXXXX-X
copyright = "Cyrus Yip"            # default: author.name ↓        # 默认为下面配置的author.name ↓
enableGitInfo = true      # use git commit log to generate lastmod record # 可根据 Git 中的提交生成最近更新记录。
summaryLength = 100

# Highlight options. See https://gohugo.io/content-management/syntax-highlighting/
pygmentsCodeFences = true # Enable syntax highlighting with GitHub flavoured code fences
pygmentsUseClasses = true # Use CSS classes to format highlighted code
pygmentsCodefencesGuessSyntax = true
pygmentsOptions = "linenos=table"

# Render English site under /en
defaultContentLanguageInSubdir = "true"

[permalinks]
  post = "/post/:year/:month/:day/:slug/"
# language support # en / zh-cn / other... translations present in i18n/
defaultContentLanguage = "en"           # Default language to use
[langusges]
[languages.en]
  title = "Cyrus Yip's Blog"
  languageName = "English"
  contentDir = 'content/en'
  # languageCode = "en"
  # weight = 2
[languages.zh-cn]
  title = "叶寻的博客"
  languageName = "简体中文"
  contentDir = 'content/zh-cn'
  # languageCode = "zh-cn"
  # weight = 1
[author]                  # essential                     # 必需
  name = "Cyrus Yip 叶寻"

[sitemap]                 # essential                     # 必需
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[[languages.en.menu.main]]
  name = "Home"
  weight = 10
  identifier = "home"
  url = "/"

[[languages.en.menu.main]]
  name = "Archives"
  weight = 20
  identifier = "archives"
  url = "/post/"
[[languages.en.menu.main]]
  name = "Tags"
  weight = 30
  identifier = "tags"
  url = "/tags/"

[[languages.zh-cn.menu.main]]
  name = "主页"
  weight = 10
  identifier = "home"
  url = "zh-cn/"
[[languages.zh-cn.menu.main]]
  name = "文章"
  weight = 20
  identifier = "archives"
  url = "zh-cn/post/"
[[languages.zh-cn.menu.main]]
  name = "标签"
  weight = 30
  identifier = "tags"
  url = "zh-cn/tags/"

[params]
  since = "2020"            # Site creation time          # 站点建立时间
  homeFullContent = false   # if false, show post summaries on home page. Otherwise show full content.
  rssFullContent = true     # if false, Rss feed instead of the summary

  # site info (optional)
  # logoTitle = "Jane"        # default: the title value
  keywords = ["Cyrus Yip","叶寻"]
  description = "Cyrus Yip's Blog; 叶寻的博客"
  # paginate of archives, tags and categories
  archive-paginate = 99999
  # The date format to use; for a list of valid formats, see https://gohugo.io/functions/format/
  dateFormatToUse = "2006-01-02"

  # Some global options, you can also close or open something in front matter for a single post, see more information from `archetypes/default.md`.
  toc = true
  photoswipe = true # see https://github.com/dimsemenov/PhotoSwipe # 是否启用PhotoSwipe（图片可点击）
  contentCopyright = '<a rel="license noopener" href="https://creativecommons.org/licenses/by-nc-sa/4.0/" target="_blank">CC BY-NC-SA 4.0</a>'

  # Link custom CSS and JS assets
  #   (relative to /static/css and /static/js respectively)
  customCSS = []            # if ['custom.css'], load '/static/css/custom.css' file
  customJS = []             # if ['custom.js'], load '/static/js/custom.js' file
  showMenuLanguageChooser = true

  # show word count and read time ?                       # 是否显示字数统计与阅读时间
  moreMeta = true

  [params.utteranc]         # utteranc is a comment system based on GitHub issues. see https://utteranc.es
    enable = true
    repo = "CyrusYip/blog-comment"    # The repo to store comments
    issueTerm = "pathname"

  [params.counter.busuanzi]  # a Chinese visitor counter  # 不蒜子计数器
    enable = false

  # use public git repo url to link lastmod git commit, enableGitInfo should be true.
  # 指定 git 仓库地址，可以生成指向最近更新的 git commit 的链接，需要将 enableGitInfo 设置成 true.
  # [params.gitInfo]
  #   gitRepo = "https://github.com/CyrusYip/cyrusyip-blog"
  #   showCommitMessage = true

  [params.social]                                         # 社交链接
    b-stack-overflow = "https://stackoverflow.com/users/14399237/cyrus-yip"
    c-twitter = "https://twitter.com/CyrusYip10"
    g-github = "https://github.com/CyrusYip"

# see https://gohugo.io/getting-started/configuration-markup
[markup]
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 6
    # ordered = true
 [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
