# global options[[[1
# Reference
# exampleSite/config.toml
# exampleSite/full-config.toml
# dev-config.toml
# https://gohugo.io/getting-started/configuration/

buildFuture = true
baseURL = "https://cyrusyip.org/"
title = "Cyrus Yip | 叶寻"
enableRobotsTXT = true
enableEmoji = true
theme = "jane"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]

hasCJKLanguage = true
paginate = 3              # Number of articles displayed on the homepage  # 首页每页显示的文章数
# rssLimit = 20             # Limit Entry Count to Rss file # 限制 Rss 文章输出数量
# disqusShortname = "cyrusyip"      # disqus_shortname
googleAnalytics = "UA-193139827-1"      # UA-XXXXXXXX-X
copyright = "Cyrus Yip"            # default: author.name ↓        # 默认为下面配置的author.name ↓
enableGitInfo = true      # use git commit log to generate lastmod record # 可根据 Git 中的提交生成最近更新记录。
summaryLength = 100

# Highlight options. See https://gohugo.io/content-management/syntax-highlighting/
pygmentsCodeFences = true # Enable syntax highlighting with GitHub flavoured code fences
pygmentsUseClasses = true # Use CSS classes to format highlighted code
pygmentsCodefencesGuessSyntax = true
pygmentsOptions = "linenos=table"

# Render English site under /en
defaultContentLanguageInSubdir = "true"
defaultContentLanguage = "en"
# ]]]
# permalinks, author, sitemap, markup[[[
[permalinks]
  post = "/post/:year/:month/:day/:slug/"
[author]
  name = "Cyrus Yip 叶寻"
[sitemap] # essential
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"
# see https://gohugo.io/getting-started/configuration-markup
[markup]
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 6
    # ordered = true
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
# ]]]
# Chinese and English[[[
[langusges]
[languages.en]
  title = "Cyrus Yip's Blog"
  languageName = "English"
  contentDir = 'content/en'
  languageCode = "en-US"
  # weight = 2
[languages.zh-cn]
  title = "叶寻的博客"
  languageName = "简体中文"
  contentDir = 'content/zh-cn'
  languageCode = "zh-CN"
  # weight = 1
[[languages.en.menu.main]]
  name = "Home"
  weight = 10
  identifier = "home"
  url = "/"
[[languages.en.menu.main]]
  name = "Archives"
  weight = 20
  identifier = "archives"
  url = "/post/"
[[languages.en.menu.main]]
  name = "Tags"
  weight = 30
  identifier = "tags"
  url = "/tags/"
[[languages.zh-cn.menu.main]]
  name = "主页"
  weight = 10
  identifier = "home"
  url = "zh-cn/"
[[languages.zh-cn.menu.main]]
  name = "文章"
  weight = 20
  identifier = "archives"
  url = "zh-cn/post/"
[[languages.zh-cn.menu.main]]
  name = "标签"
  weight = 30
  identifier = "tags"
  url = "zh-cn/tags/"
# ]]]
# params[[[
[params]
  since = "2020"
  homeFullContent = false
  rssFullContent = true
  showMenuLanguageChooser = true
  moreMeta = true # word count and read time

  # site info (optional)
  # logoTitle = "Jane"        # default: the title value
  keywords = ["Cyrus Yip","叶寻"]
  description = "Cyrus Yip's Blog; 叶寻的博客"
  archive-paginate = 99999
  # The date format to use; for a list of valid formats, see https://gohugo.io/functions/format/
  dateFormatToUse = "2006-01-02"

  toc = true
  photoswipe = true # image gallery and lightbox
  contentCopyright = '<a rel="license noopener" href="https://creativecommons.org/licenses/by-nc-sa/4.0/" target="_blank">CC BY-NC-SA 4.0</a>'

  # Link custom CSS and JS assets
  #   (relative to /static/css and /static/js respectively)
  customCSS = ['custom.css'] # /static/css/custom.css
  customJS = []              # if ['custom.js'], load '/static/js/custom.js' file

  # [params.utteranc]
  #   enable = true
  #   repo = "CyrusYip/blog-comment"    # The repo to store comments
  #   issueTerm = "pathname"
  [params.counter.busuanzi]  # a Chinese visitor counter  # 不蒜子计数器
    enable = false
  # [params.gitInfo] # show link to lastmod commit, enableGitInfo should be true
  #   gitRepo = "https://github.com/CyrusYip/cyrusyip-blog"
  #   showCommitMessage = true
  [params.social]                                         # 社交链接
    b-stack-overflow = "https://stackoverflow.com/users/14399237/cyrus-yip"
    c-twitter = "https://twitter.com/CyrusYip10"
    g-github = "https://github.com/CyrusYip"
# ]]]
# vim:foldmethod=marker:foldmarker=[[[,]]]
